name: flutter_news
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  flutter_advanced_networkimage: ^0.3.4
  shared_preferences: ^0.4.2
  url_launcher: ^3.0.3
  firebase_auth: ^0.5.15
  google_sign_in: ^3.0.4
  firebase_database: ^1.0.3
  firebase_core: ^0.2.5
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true